name: make lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      - name: npm install
        # Install project
        run: |
          make install
        # Add environment variables
        env:
          CI: true
    - name: Run linter
      run: |
        make lint
